apiVersion: kuttl.dev/v1beta1
kind: TestSuite
testDirs:
  - ./tests/
commands:
  - command: helm upgrade --install crossplane crossplane-stable/crossplane --namespace crossplane-system --create-namespace --wait
  - command: helm upgrade --install atlas-operator oci://ghcr.io/ariga/charts/atlas-operator --namespace atlas-operator --create-namespace --wait
  - command: kubectl apply --filename providers/aws.yaml
  - command: kubectl apply --filename providers/sql.yaml
  - command: kubectl apply --filename providers/provider-kubernetes-incluster.yaml
  - command: kubectl apply --filename package/definition.yaml
  - command: kubectl apply --filename package/aws.yaml
  - command: kubectl apply --filename providers/function-patch-and-transform.yaml
  - command: kubectl apply --filename providers/function-go-templating.yaml
  - command: kubectl apply --filename providers/function-auto-ready.yaml
  - command: kubectl wait --for condition=Healthy provider/provider-aws-rds --timeout=300s
  - command: kubectl wait --for condition=Healthy provider/provider-aws-ec2 --timeout=300s
  - command: kubectl wait --for condition=Healthy provider/upbound-provider-family-aws --timeout=300s
  - command: kubectl wait --for condition=Healthy function/crossplane-contrib-function-patch-and-transform --timeout=300s
  - command: kubectl wait --for condition=Healthy function/upbound-function-go-templating --timeout=300s
  - command: kubectl wait --for condition=Healthy function/upbound-function-auto-ready --timeout=300s
timeout: 30
# startKIND: true
# kindNodeCache: true
# skipDelete: true
# skipClusterDelete: true
