name: Build
on:
  push:
    branches:
      - main
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install Pkl
        run: |
          curl -L -o pkl-binary https://github.com/apple/pkl/releases/download/0.25.2/pkl-linux-amd64
          chmod +x pkl-binary
          mv pkl-binary /usr/local/bin/pkl
          echo $PATH
      - name: Install Devbox
        uses: jetpack-io/devbox-install-action@v0.6.0
      - name: Build the package
        run: |
          devbox run package-publish
      # - name: Build the package
      #   run: |
      #     cd package
      #     curl -sL https://cli.upbound.io | sh
      #     ./up login --token ${{ secrets.UP_TOKEN }}
      #     ./up xpkg build --name sql.xpkg
      #     ./up xpkg push --package sql.xpkg xpkg.upbound.io/${{ secrets.UP_ACCOUNT }}/dot-sql:v0.8.${{ github.run_number }}
      #     rm sql.xpkg
      # - name: Update config
      #   run: |
      #     yq --inplace ".spec.package = \"xpkg.upbound.io/devops-toolkit/dot-sql:v0.8.${{ github.run_number }}\"" config.yaml
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Config update [skip ci]"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CROSSPLANE_TOKEN }}
          branch: ${{ github.ref }}
